// <auto-generated />
using System;
using DeepDive11.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeepDive11.Migrations
{
    [DbContext(typeof(DeepDiveContext))]
    [Migration("20260919191743_AddUserIdToBooking")]
    partial class AddUserIdToBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeepDive11.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DeepDive11.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.ToTable("_bookings");
                });

            modelBuilder.Entity("DeepDive11.Models.BookingProduct", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("_bookingProducts");
                });

            modelBuilder.Entity("DeepDive11.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DeepDive11.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DeepDive11.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("IncludedItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.Property<int?>("ProductGender")
                        .HasColumnType("int");

                    b.Property<int?>("ProductSize")
                        .HasColumnType("int");

                    b.Property<string>("SecondStage")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Sizes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Thickness")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Volume")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("_products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "Scubapro",
                            Category = "BCD",
                            Image = "NavigatorLiteBCD.webp",
                            Model = "Navigator Lite BCD",
                            PricePerDay = 125,
                            Sizes = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "Scubapro",
                            Category = "BCD",
                            Image = "BCDGlide.webp",
                            Model = "BCD Glide",
                            PricePerDay = 140,
                            Sizes = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "Scubapro",
                            Category = "BCD",
                            Image = "HydrosPro.webp",
                            Model = "BCD Hydros Pro",
                            PricePerDay = 200,
                            Sizes = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "Seac",
                            Category = "BCD",
                            Image = "BCDModular.webp",
                            Model = "BCD Modular",
                            PricePerDay = 145,
                            Sizes = "[\"S\",\"M\",\"L\"]"
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "Scubapro",
                            Category = "Dykkerdragter",
                            Image = "Våddragt.jpeg",
                            Model = "Definition",
                            PricePerDay = 100,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Thickness = 3.0,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "Scubapro",
                            Category = "Dykkerdragter",
                            Image = "Våddragt.jpeg",
                            Model = "Definition",
                            PricePerDay = 100,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Thickness = 5.0,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "Scubapro",
                            Category = "Dykkerdragter",
                            Image = "Våddragt.jpeg",
                            Model = "Definition",
                            PricePerDay = 100,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Thickness = 7.0,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "Waterproof",
                            Category = "Dykkerdragter",
                            Image = "Våddragt.jpeg",
                            Model = "W5",
                            PricePerDay = 100,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Thickness = 3.5,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "Fourth Element",
                            Category = "Dykkerdragter",
                            Image = "Våddragt.jpeg",
                            Model = "Proteus",
                            PricePerDay = 120,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Thickness = 5.0,
                            Type = "Våddragt"
                        },
                        new
                        {
                            ProductId = 10,
                            Brand = "Scubapro",
                            Category = "Dykkerdragter",
                            Image = "Tørdragt.webp",
                            Model = "Exodry 4.0",
                            PricePerDay = 300,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            ProductId = 11,
                            Brand = "Waterproof",
                            Category = "Dykkerdragter",
                            Image = "Tørdragt.webp",
                            Model = "D7 Evo",
                            PricePerDay = 320,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            ProductId = 12,
                            Brand = "Santi",
                            Category = "Dykkerdragter",
                            Image = "Tørdragt.webp",
                            Model = "E.Lite Plus",
                            PricePerDay = 350,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            ProductId = 13,
                            Brand = "Scubapro",
                            Category = "Tanke",
                            Image = "Tank.jpg",
                            Model = "Tank 5 liter",
                            PricePerDay = 150,
                            Volume = 5
                        },
                        new
                        {
                            ProductId = 14,
                            Brand = "Scubapro",
                            Category = "Tanke",
                            Image = "Tank.jpg",
                            Model = "Tank 10 liter",
                            PricePerDay = 160,
                            Volume = 10
                        },
                        new
                        {
                            ProductId = 15,
                            Brand = "Scubapro",
                            Category = "Tanke",
                            Image = "Tank.jpg",
                            Model = "Tank 12 liter",
                            PricePerDay = 170,
                            Volume = 12
                        },
                        new
                        {
                            ProductId = 16,
                            Brand = "Scubapro",
                            Category = "Tanke",
                            Image = "Tank.jpg",
                            Model = "Tank 15 liter",
                            PricePerDay = 180,
                            Volume = 15
                        },
                        new
                        {
                            ProductId = 17,
                            Brand = "Scubapro",
                            Category = "Maske og Snorkel",
                            Image = "GhostMaske.jpg",
                            Model = "Ghost",
                            PricePerDay = 50
                        },
                        new
                        {
                            ProductId = 18,
                            Brand = "Scubapro",
                            Category = "Maske og Snorkel",
                            Image = "DMask.jpg",
                            Model = "D-Mask",
                            PricePerDay = 60
                        },
                        new
                        {
                            ProductId = 19,
                            Brand = "Scubapro",
                            Category = "Maske ogSnorkel",
                            Image = "SpectraMini.jpg",
                            Model = "Spectra Mini",
                            PricePerDay = 50
                        },
                        new
                        {
                            ProductId = 20,
                            Brand = "Scubapro",
                            Category = "Maske og Snorkel",
                            Image = "CrystalVU.jpg",
                            Model = "Crystal VU",
                            PricePerDay = 75
                        },
                        new
                        {
                            ProductId = 21,
                            Brand = "Fourth Element",
                            Category = "Maske og Snorkel",
                            Image = "ScoutKontrast.jpg",
                            Model = "Scout Kontrast",
                            PricePerDay = 75
                        },
                        new
                        {
                            ProductId = 22,
                            Brand = "Fourth Element",
                            Category = "Maske og Snorkel",
                            Image = "ScoutEnhance.webp",
                            Model = "Scout Enhance",
                            PricePerDay = 75
                        },
                        new
                        {
                            ProductId = 23,
                            Brand = "Tusa",
                            Category = "Maske og Snorkel",
                            Image = "TUSA.jpg",
                            Model = "Element",
                            PricePerDay = 75
                        },
                        new
                        {
                            ProductId = 24,
                            Brand = "Scubapro",
                            Category = "Finner",
                            Image = "JetFin.webp",
                            Model = "Jet Fin",
                            PricePerDay = 50,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            ProductId = 25,
                            Brand = "Scubapro",
                            Category = "Finner",
                            Image = "GOTravel.webp",
                            Model = "GO Travel",
                            PricePerDay = 50,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            ProductId = 26,
                            Brand = "Scubapro",
                            Category = "Finner",
                            Image = "SuperNova.webp",
                            Model = "Seawing Supernova",
                            PricePerDay = 60,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            ProductId = 27,
                            Brand = "Seac",
                            Category = "Finner",
                            Image = "Propulsion.webp",
                            Model = "Propulsion",
                            PricePerDay = 50,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            ProductId = 28,
                            Brand = "Seac",
                            Category = "Finner",
                            Image = "ALA.webp",
                            Model = "ALA",
                            PricePerDay = 50,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            ProductId = 29,
                            Brand = "Fourth Element",
                            Category = "Finner",
                            Image = "Tech",
                            Model = "Tech",
                            PricePerDay = 75,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            ProductId = 30,
                            Brand = "Fourth Element",
                            Category = "Finner",
                            Image = "RecFin.jpg",
                            Model = "Rec Fin",
                            PricePerDay = 80,
                            Sizes = "[\"XS\",\"S\",\"M\",\"L\",\"XL\"]"
                        },
                        new
                        {
                            ProductId = 31,
                            Brand = "Scubapro",
                            Category = "Regulatorsæt",
                            FirstStage = "MK25EVO",
                            Image = "RegulatorSæt31.webp",
                            Octopus = "R105",
                            PricePerDay = 125,
                            SecondStage = "S600"
                        },
                        new
                        {
                            ProductId = 32,
                            Brand = "Scubapro",
                            Category = "Regulatorsæt",
                            FirstStage = "MK17EVO",
                            Image = "RegulatorSæt32.jpg",
                            Octopus = "R095",
                            PricePerDay = 100,
                            SecondStage = "C370"
                        },
                        new
                        {
                            ProductId = 33,
                            Brand = "Scubapro",
                            Category = "Regulatorsæt",
                            FirstStage = "MK25EVO BT",
                            Image = "RegulatorSæt33.webp",
                            Octopus = "S270",
                            PricePerDay = 150,
                            SecondStage = "A700 Carbon BT"
                        },
                        new
                        {
                            ProductId = 34,
                            Brand = "Dive Deep",
                            Category = "Komplette sæt",
                            Image = "DykkerSæt.jpg",
                            IncludedItems = "[\"BCD\",\"Dykkerdragt\",\"Regulators\\u00E6t\",\"Tank\",\"Finner\",\"Maske\",\"Snorkel\"]",
                            Model = "Komplet dykkersæt",
                            PricePerDay = 760
                        },
                        new
                        {
                            ProductId = 35,
                            Brand = "Dive Deep",
                            Category = "Komplette sæt",
                            Image = "snorkelsæt.webp",
                            IncludedItems = "[\"Maske\",\"Snorkel\",\"Finner\"]",
                            Model = "Komplet snorkelsæt",
                            PricePerDay = 650
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3bc0bf8b-fa7f-410e-8aa8-6aec18b8da12",
                            ConcurrencyStamp = "a68e4ad2-7951-44e7-a0f2-a621fa087641",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "c3498dbf-f53a-4c31-ac76-fdb342803cee",
                            ConcurrencyStamp = "96767fe8-e303-4990-92ac-37fd9bbfd78c",
                            Name = "customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DeepDive11.Models.BookingProduct", b =>
                {
                    b.HasOne("DeepDive11.Models.Booking", "Booking")
                        .WithMany("BookingProducts")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeepDive11.Models.Products", "Product")
                        .WithMany("BookingProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DeepDive11.Models.OrderItem", b =>
                {
                    b.HasOne("DeepDive11.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DeepDive11.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DeepDive11.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeepDive11.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DeepDive11.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeepDive11.Models.Booking", b =>
                {
                    b.Navigation("BookingProducts");
                });

            modelBuilder.Entity("DeepDive11.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DeepDive11.Models.Products", b =>
                {
                    b.Navigation("BookingProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
